apiVersion: v1
kind: Service
metadata:
  name: reading-list-api
  labels:
    app: reading-list-api
spec:
  type: ClusterIP
  selector:
    app: reading-list-api
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
